# Đặt phiên bản iOS tối thiểu cho dự án của bạn
platform :ios, '15.0'
# Vô hiệu hóa thu thập dữ liệu thống kê CocoaPods
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Cấu hình dự án 'Runner'
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}
# Hàm để tìm Flutter root
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end
# Import helper từ Flutter
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup
# Cấu hình target 'Runner' và các thư viện khác
target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # pod 'Firebase/Messaging'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
       # Đặt phiên bản triển khai iOS
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      # Đảm bảo các thiết lập CocoaPods được kế thừa
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
      # Loại bỏ kiến trúc arm64 trên bộ mô phỏng (để tránh xung đột)
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      # Tùy chọn: Thiết lập tối ưu hóa trình biên dịch
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
    end
  end
end
